### ISSUE TITLE
Expose additional parameters in Leiden and Louvain

### ISSUE THREAD

**Issue by jpintar** [scverse/rapids_singlecell#101]
There are a couple of parameters in the cuGraph implementation of `leiden` and `louvain` that cannot be accessed from `rapids_singlecell`:
- `random_state` can be set in both the cuGraph and Scanpy versions of `leiden`
- `threshold` is available in the cuGraph version of `louvain`
- `theta` is nominally available in the cuGraph version of `leiden`, but it currently does nothing due to a couple of bugs

The first two are a quick thing to fix, so I'm going to submit two pull requests, one for `leiden` and one for `louvain` (and I'll be happy to submit another one for `theta`, too, when it's fixed in cuGraph).

**Comment by Intron7** [comment]
Hey @jpintar 

Thank you for the PR. I'm on holiday until January so it will sadly take some time until I can address those. I also saw that something with the CI install went wrong, but this is on my side. 

Yours Severin

**Comment by Intron7** [comment]
@jpintar thanks for the great PRs
