### ISSUE TITLE
normalize_total slower than CPU implementation

### ISSUE THREAD

**Issue by jpintar** [scverse/rapids_singlecell#111]
Averaging over 130 runs of a trial dataset (15,000 × 15,000) on a variety of GPUs and CPUs, I've noticed that `rsc.pp.normalize_total()` is slower than `scanpy.pp.normalize_total()` by a factor of around 4.5. In the best case, the average over ten runs on an NVIDA A100 was 2.06 times slower than running the Scanpy version on a Xeon Platinum 8358. In the worst case, the average over ten runs on a GeForce GTX 1080 Ti was 8.85 times slower than running on a Xeon E5-2697 v4. I haven't had time to look under the hood and figure out what's going on, but I thought I should let you know.

rapids-singlecell 0.9.3
RAPIDS 23.12
CUDA 11.8
CuPy 12.3
Scanpy 1.9.6

**Comment by Intron7** [comment]
@jpintar i don't think this is a bug. 15000 cells is not an amount of cells where acceleration shines. What format is your matrix (csr, csc, c or f-continuous)? You also have to account for compile times for the gpu kernel, but that's only the first launch. I can look into the kernels for more optimisations. Can you also please share the real runtime and not just ratios.

**Comment by jpintar** [comment]
Thanks! This was with a csr-matrix, and throwing out the first run-times. The real average runtimes were 0.110337s on CPU vs 0.513284s on GPU (I can also break those down by CPU/GPU model if that would be helpful). It just stood out as the only step in a toy analysis (`pp.highly_variable_genes`, `pp.normalize_total`, `pp.log1p`, `pp.pca`, `pp.neighbors`, `tl.leiden`) where the GPU version wasn't a massive improvement.

**Comment by Intron7** [comment]
Ok that's actually slower than expected. Did you provide a target_sum?

**Comment by jpintar** [comment]
No `target_sum`.

**Comment by Intron7** [comment]
Ahh ok. I think that's the bottleneck then. Try it with 10000. I think that will be a lot faster.

**Comment by jpintar** [comment]
That was it! With `target_sum=10000`, over seven sets of ten runs, the average time for `pp.normalze_total` on CPU was 0.11058307s (so basically same as before), but only 0.00009686s on GPU. With this, GPU-to-CPU run-time ratio for the whole toy workflow was 0.12.

**Comment by Intron7** [comment]
I'll check if I can speed up the median calculation

**Comment by Intron7** [comment]
I ran some tests. I can't reproduce the numbers you are getting. For my test dataset (92666, 25660) I get 43.4 ms for GPU and 471ms for CPU without `target_sum`. With `target_sum=10000` I get 11.5 ms on GPU vs 467 ms on CPU. Thats all without with `inplace=False`.

Is `normalize_total` the first thing you do in your workflow?

**Comment by jpintar** [comment]
Yes, `normalize_total` is the first step. Not sure what's causing the discrepancy. I tested again with a larger dataset (100,000 × 25,000) on a Xeon Platinum 8352S/NVIDIA A100 80GB node and got (averaged over ten runs):
- without `target_sum`: 1.870052s on GPU, 0.893860s on CPU
- with `target_sum=10000`: 0.000127s on GPU, 0.891473s on CPU
- without `target_sum` and with `inplace=False`: 1.873045s on GPU, 1.321668s on CPU
- with `target_sum=10000` and with `inplace=False`: 0.000284s on GPU, 1.348362s on CPU

On this platform, the original smaller dataset (15,000 × 15,000) gives me:
- without `target_sum`: 0.194899s on GPU, 0.107211s on CPU
- with `target_sum=10000`: 0.000117s on GPU, 0.107495s on CPU
- without `target_sum` and with `inplace=False`: 0.195746s on GPU, 0.160107s on CPU
- with `target_sum=10000` and with `inplace=False`: 0.000266s on GPU, 0.163338 on CPU

**Comment by Intron7** [comment]
I just can't reproduce it. I run my tests on and A100 80GB PCIe. The dataset I use for testing, is the lung dataset from the notebooks. It would be nice if you could also use it once just to be 100% sure. My initial concern was that the data just wasn't loaded properly yet. But since you average over 10 runs that can't be the case. I wrote a new kernel for the sparse sum. This is slightly faster.  Do you use 32 or 64 bit?

**Comment by jpintar** [comment]
Sorry about the delay - was travelling so I couldn't get to this immediately.

The data are all `float32`. But things keep getting stranger. I downloaded the Qian *et al*. lung dataset (93,575 × 33,694) from the sample notebooks, and reran my test script on both it and my 100,000 × 25,000 toy dataset, in fresh minimal `conda` environments that differ only in the `rapids-singlecell` version. I'm getting the following (all times in seconds, again averaging over ten runs after dropping the first run):

<table>
  <tr>
    <td></td>
    <td colspan="4"><b>Toy dataset</b></td>
    <td colspan="4"><b>Lung dataset</b></td>
  </tr>
  <tr>
    <td></td>
    <td><code>0.9.2</code></td>
    <td><code>0.9.3</code></td>
    <td><code>0.9.4</code></td>
    <td><code>0.9.5</code></td>
    <td><code>0.9.2</code></td>
    <td><code>0.9.3</code></td>
    <td><code>0.9.4</code></td>
    <td><code>0.9.5</code></td>
  </tr>
  <tr>
    <td>CPU, no&nbsp<code>target_sum</code></td>
    <td>0.898468</td>
    <td>0.889558</td>
    <td>0.889898</td>
    <td>0.889566</td>
    <td>0.495055</td>
    <td>0.492184</td>
    <td>0.492184</td>
    <td>0.493177</td>
  </tr>
  <tr>
    <td>GPU, no&nbsp<code>target_sum</code></td>
    <td>1.887408</td>
    <td>1.888572</td>
    <td>0.020584</td>
    <td>0.020677</td>
    <td>0.012107</td>
    <td>0.012067</td>
    <td>0.010960</td>
    <td>0.010956</td>
  </tr>
  <tr>
    <td>CPU, <code>target_sum=10000</code></td>
    <td>0.898757</td>
    <td>0.887722</td>
    <td>0.888544</td>
    <td>0.889203</td>
    <td>0.494149</td>
    <td>0.490748</td>
    <td>0.491338</td>
    <td>0.491512</td>
  </tr>
  <tr>
    <td>GPU, <code>target_sum=10000</code></td>
    <td>0.000042</td>
    <td>0.000042</td>
    <td>0.000039</td>
    <td>0.000038</td>
    <td>0.000040</td>
    <td>0.000040</td>
    <td>0.000039</td>
    <td>0.000039</td>
  </tr>
</table>

So no slowdown with the lung dataset, just as in your tests. But also no slowdown with my toy dataset with versions after `0.9.3`, and as far as I know nothing changed between `0.9.3` and `0.9.4` that accounts for this. And I don't see anything particularly anomalous about my toy dataset - only that it's denser than the lung dataset (8.3% non-zero vs. 3.6%). It was generated by randomly downsampling (with replacement) from real (unpublished) data.

**Comment by Intron7** [comment]
I added a new special algorithm that does the summation across the major axis for csr matrices with #112 in v0.9.3. This worked a lot better than I expected for your data. cupy does the summation with a matrix multiplication. I have a custom logic now, that works a little bit different and relays less on atomics. Maybe I should open a PR with this for Cupy.

**Comment by jpintar** [comment]
Awesome! Thank you for looking into this!
