### ISSUE TITLE
Output from harmony step: rsc.pp.harmony_integrate(Bdata,key="orig.ident"), isn't used in constructing neighborhood graph of cells: rsc.pp.neighbors(Bdata,n_neighbors=15, n_pcs=50) 

### ISSUE THREAD

**Issue by 31474molly** [scverse/rapids_singlecell#121]
Hi!
I noticed that the output from harmony step: rsc.pp.harmony_integrate(Bdata,key="orig.ident"), isn't used in constructing neighborhood graph of cells: rsc.pp.neighbors(Bdata,n_neighbors=15, n_pcs=50). Because I got the same UMAP result even though I skip the harmony step. The graph after hamony step is as follows (The batch effect is obvious)
![bef6a6943a636c0bb0dbb76aa27f68d](https://github.com/scverse/rapids_singlecell/assets/119156768/aa5fd125-dcdc-44d6-9bdc-8f013dde86f6)
So I used the code: rsc.pp.neighbors(Bdata,n_neighbors=15, n_pcs=50,use_rep='X_pca_harmony'). Better integration between samples may be got. Is it correct to use the "use_rep='X_pca_harmony' ?
Thanks a lot!

**Comment by Intron7** [comment]
Hey @31474molly,

Can you please share the output from the harmony integration. I think in general your workflow seems to be correct. Can you also show the uncorrected UMAP to see if harmony did anything/ reduced the batch effect? 
Also to see batch effects I always like embedding density.

**Comment by 31474molly** [comment]
Thank you for your prompt reply!
There are my codes and corresponding output image:
A.without "use_rep='X_pca_harmony'"
rsc.pp.normalize_total(Bdata, target_sum=1e4)
rsc.pp.log1p(Bdata)
rsc.pp.highly_variable_genes(Bdata,n_top_genes=5000,flavor="seurat_v3",layer = "counts")
rsc.utils.anndata_to_CPU(Bdata, layer="counts")
Bdata = Bdata[:,Bdata.var["highly_variable"]==True]
rsc.pp.regress_out(Bdata,keys=["total_counts", "pct_counts_MT"])
rsc.pp.scale(Bdata,max_value=10)
rsc.pp.pca(Bdata,n_comps = 100)
sc.pl.pca_variance_ratio(Bdata, log=True,n_pcs=100)
rsc.utils.anndata_to_CPU(Bdata, convert_all=True)
rsc.pp.harmony_integrate(Bdata,key="orig.ident")
rsc.pp.neighbors(Bdata,n_neighbors=15, n_pcs=50) 
rsc.tl.umap(Bdata,min_dist=0.3)
rsc.tl.leiden(Bdata,resolution=0.5)
![03 UMAP_cluster](https://github.com/scverse/rapids_singlecell/assets/119156768/3507cc98-a44a-4f6b-9af4-54faf476011a)


B.with "use_rep='X_pca_harmony'"
rsc.pp.neighbors(Bdata,n_neighbors=15, n_pcs=50,use_rep='X_pca_harmony')  
the rest part is the same as part A
![332df0c9805a23758e85c554a8688e9](https://github.com/scverse/rapids_singlecell/assets/119156768/13df7603-1dce-487f-9600-50b1e093f166)


And I noticed the corresponding part in your tutorial:
<img width="1247" alt="71b866fe7f33b2e5b80c8e4d7458d6b" src="https://github.com/scverse/rapids_singlecell/assets/119156768/b78f5d3e-0c90-4871-8a55-65090c9d5b44">


Thanks a lot!

**Comment by Intron7** [comment]
The tutorial doesn't use of the X_pca_harmony for neighbors, because I just wanted to show the speed. However the rest of your workflow looks good. I think that you can see here that harmony does it's job quite nicely when you use it with neighbors. I'll mention in the tutorial that you need to set X_pca_harmony if you want to use it.

**Comment by 31474molly** [comment]
Of course! Thank you very much.
