### ISSUE TITLE
Attribute error in notebooks

### ISSUE THREAD

**Issue by knollr** [scverse/rapids_singlecell#138]
**Describe the bug**
Thanks for this very nice tool! I found that the very first step shown in the notebook where I convert my anndata to GPU is not working as rapids_singlecell has no attribute "get". 

**Steps/Code to reproduce bug**
`import rapids_singlecell as rsc # version 0.9.6`

`rsc.get.anndata_to_GPU(adata)`

**Solution**
I found the correct function under "utils":
`rsc.utils.anndata_to_GPU(adata)`

**Comment by Intron7** [comment]
That is correct. For the upcoming version 0.10.0 I switched the `utils` function to `get` since there is only the GPU conversion in there. The stable documentation https://rapids-singlecell.readthedocs.io/en/stable/api/utils.html still reflects the behavior for the current version 0.9.6.
