### ISSUE TITLE
Adding other DE methods into rapids_singlecell

### ISSUE THREAD

**Issue by SNOL2** [scverse/rapids_singlecell#163]
Hi. I was wondering if DE methods in scanpy could be added into rapids_singlecell, e.g. wilcoxon test. Additionally, could rapids_singlecell return log2FC and fraction of cells expressing the genes?
Thanks in advance!

**Comment by Intron7** [comment]
@SNOL2 I don't know how well wilcoxon and other methods like this will scale on the GPU. For advanced DEG testing I would recommend using pesudo-bulk with pyDESeq2
