### ISSUE TITLE
[QST] QC kernels

### ISSUE THREAD

**Issue by dyuan1111** [scverse/rapids_singlecell#165]
**What is your question?**
I'm new to cuda computing. Please bear with me :). 

https://github.com/scverse/rapids_singlecell/tree/main/src/rapids_singlecell/preprocessing/_kernels/_qc_kernels.py

In this script for defining cuda kernels for calculating qc metrics, specifically for the kernel named "_sparse_qc_kernel_csr", why the updates on sums_cells and cell_ex are inside the for loop that loops over all genes? The indentation is also different for these two lines of codes compared to the previous codes inside that for loop.

Thanks so much!

**Comment by Intron7** [comment]
@dyuan1111 so the whole function is nothing but a loop written in cuda/c. Since the function works on each row of a csr matrix each gene contributes to that cell. With this setup I start the kernel for each cell. Since I want the qc information for each gene, I have to update those arrays with atomics (those are threadsafe updates) within the loop. For the cells I can sum up all values within the loop but I update the result arrays outside of it. That a bit more efficient because of the memory layout and being able to use cache.

**Comment by dyuan1111** [comment]
Thank you so much for the explanation! Really appreciate it.

You mentioned that "For the cells I can sum up all values within the loop but I update the result arrays outside of it". In the codes, the for loop is the following. Isn't it that the result arrays (sums_cells and cell_ex) are updated inside the loop, not outside of the loop, based on the brackets?

        {0} sums_cells_i = 0;
        int cell_ex_i = 0;
        for(int gene = start_idx; gene < stop_idx; gene++){
            {0} value = data[gene];
            int gene_number = index[gene];
            atomicAdd(&sums_genes[gene_number], value);
            sums_cells_i += value;
            atomicAdd(&gene_ex[gene_number], 1);
            cell_ex_i += 1;
        sums_cells[cell] = sums_cells_i;
        cell_ex[cell] = cell_ex_i;
        }

**Comment by Intron7** [comment]
Yes but those are values and not the results arrays.

**Comment by dyuan1111** [comment]
Just to clarify, for each cell, the for loop iterates over all genes that had non-0 counts. sums_cells_i and cell_ex_i get updated for each non-0 value. My understanding is that after the iteration of all non-0 genes for that one cell, sums_cells_i is the sum of gene counts, and cell_ex_i is # of genes that is expressed in that one cell. Shouldn't the arrays sums_cells and cell_ex be updated outside of the for loop?

**Comment by Intron7** [comment]
You are right. I updated the kernels now. There is a PR. This shouldn't really have impacted performance much. But thanks for pointing it out.

**Comment by dyuan1111** [comment]
oh thanks!! I understand it now why it doesn't affect the results. Although sums_cells[cell] and cell_ex[cell] would be overwritten over and over again, their final values would still be what are expected for sums_cells_i and cell_ex_i after iteration.
