### ISSUE TITLE
[BUG]CUDADriverError: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered

### ISSUE THREAD

**Issue by lxinq2002** [scverse/rapids_singlecell#253]
**Describe the bug**

I made an error while studying the 1 Million Brain Cells notebook.
When I didn't extract one million cells
`adata = adata[:1_000_000, :].copy()`
An error occurred in this step:
```
rsc.pp.calculate_qc_metrics(adata, qc_vars=["MT"])
```
error message：

```
---------------------------------------------------------------------------
CUDADriverError                           Traceback (most recent call last)
File <timed eval>:1

File [~/anaconda3/envs/rapids_singlecell/lib/python3.11/site-packages/rapids_singlecell/preprocessing/_simple.py:73](http://10.8.100.215:10234/lab/tree/Scanpy_test/immune/anaconda3/envs/rapids_singlecell/lib/python3.11/site-packages/rapids_singlecell/preprocessing/_simple.py#line=72), in calculate_qc_metrics(adata, expr_type, var_type, qc_vars, log1p, layer)
     26 """\
     27 Calculates basic qc Parameters. Calculates number of genes per cell (n_genes) and number of counts per cell (n_counts).
     28 Loosely based on calculate_qc_metrics from scanpy [Wolf et al. 2018]. Updates :attr:`~anndata.AnnData.obs` and :attr:`~anndata.AnnData.var`  with columns with qc data.
   (...)
     68 
     69 """
     71 X = _get_obs_rep(adata, layer=layer)
---> 73 _check_gpu_X(X)
     75 sums_cells = cp.zeros(X.shape[0], dtype=X.dtype)
     76 sums_genes = cp.zeros(X.shape[1], dtype=X.dtype)

File [~/anaconda3/envs/rapids_singlecell/lib/python3.11/site-packages/rapids_singlecell/preprocessing/_utils.py:131](http://10.8.100.215:10234/lab/tree/Scanpy_test/immune/anaconda3/envs/rapids_singlecell/lib/python3.11/site-packages/rapids_singlecell/preprocessing/_utils.py#line=130), in _check_gpu_X(X, require_cf)
    129     return True
    130 elif issparse(X):
--> 131     if X.has_canonical_format or not require_cf:
    132         return True
    133     else:

File [~/anaconda3/envs/rapids_singlecell/lib/python3.11/site-packages/cupyx/scipy/sparse/_compressed.py:676](http://10.8.100.215:10234/lab/tree/Scanpy_test/immune/anaconda3/envs/rapids_singlecell/lib/python3.11/site-packages/cupyx/scipy/sparse/_compressed.py#line=675), in _compressed_sparse_matrix.__get_has_canonical_format(self)
    673 elif not hasattr(self, '_has_canonical_format'):
    674     is_canonical = self._has_canonical_format_kern(
    675         self.indptr, self.indices, size=self.indptr.size-1)
--> 676     self._has_canonical_format = bool(is_canonical.all())
    677 return self._has_canonical_format

File cupy/_core/core.pyx:1175, in cupy._core.core._ndarray_base.all()

File cupy/_core/core.pyx:1177, in cupy._core.core._ndarray_base.all()

File cupy/_core/_routines_logic.pyx:8, in cupy._core._routines_logic._ndarray_all()

File cupy/_core/_reduction.pyx:618, in cupy._core._reduction._SimpleReductionKernel.__call__()

File cupy/_core/_reduction.pyx:370, in cupy._core._reduction._AbstractReductionKernel._call()

File cupy/_core/_cub_reduction.pyx:690, in cupy._core._cub_reduction._try_to_call_cub_reduction()

File cupy/_core/_cub_reduction.pyx:527, in cupy._core._cub_reduction._launch_cub()

File cupy/_core/_cub_reduction.pyx:462, in cupy._core._cub_reduction._cub_two_pass_launch()

File cupy/_util.pyx:64, in cupy._util.memoize.decorator.ret()

File cupy/_core/_cub_reduction.pyx:241, in cupy._core._cub_reduction._SimpleCubReductionKernel_get_cached_function()

File cupy/_core/_cub_reduction.pyx:224, in cupy._core._cub_reduction._create_cub_reduction_function()

File cupy/_core/core.pyx:2283, in cupy._core.core.compile_with_cache()

File [~/anaconda3/envs/rapids_singlecell/lib/python3.11/site-packages/cupy/cuda/compiler.py:498](http://10.8.100.215:10234/lab/tree/Scanpy_test/immune/anaconda3/envs/rapids_singlecell/lib/python3.11/site-packages/cupy/cuda/compiler.py#line=497), in _compile_module_with_cache(source, options, arch, cache_dir, extra_source, backend, enable_cooperative_groups, name_expressions, log_stream, jitify)
    494     return _compile_with_cache_hip(
    495         source, options, arch, cache_dir, extra_source, backend,
    496         name_expressions, log_stream, cache_in_memory)
    497 else:
--> 498     return _compile_with_cache_cuda(
    499         source, options, arch, cache_dir, extra_source, backend,
    500         enable_cooperative_groups, name_expressions, log_stream,
    501         cache_in_memory, jitify)

File [~/anaconda3/envs/rapids_singlecell/lib/python3.11/site-packages/cupy/cuda/compiler.py:568](http://10.8.100.215:10234/lab/tree/Scanpy_test/immune/anaconda3/envs/rapids_singlecell/lib/python3.11/site-packages/cupy/cuda/compiler.py#line=567), in _compile_with_cache_cuda(source, options, arch, cache_dir, extra_source, backend, enable_cooperative_groups, name_expressions, log_stream, cache_in_memory, jitify)
    566             cubin_hash = _hash_hexdigest(cubin).encode('ascii')
    567             if hash == cubin_hash:
--> 568                 mod.load(cubin)
    569                 return mod
    570 else:
    571     # Enforce compiling -- the resulting kernel will be cached elsewhere,
    572     # so we do nothing

File cupy/cuda/function.pyx:263, in cupy.cuda.function.Module.load()

File cupy/cuda/function.pyx:265, in cupy.cuda.function.Module.load()

File cupy_backends/cuda/api/driver.pyx:226, in cupy_backends.cuda.api.driver.moduleLoadData()

File cupy_backends/cuda/api/driver.pyx:63, in cupy_backends.cuda.api.driver.check_status()

CUDADriverError: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
```

There were no errors when I intercepted one million cells.

This doesn't seem to be due to the number of cells. I have another dataset with 1.9 million cells. If not truncated, or if more than 1.7 million cells are truncated, the same error will be reported. However, if less than 1.7 million cells are truncated, there will be no error.

This is my code

```
import scanpy as sc
import cupy as cp
import rapids_singlecell as rsc
import time
import rmm
from rmm.allocators.cupy import rmm_cupy_allocator
rmm.reinitialize(
    managed_memory=True,  
    pool_allocator=True,  
    devices=0  
)
cp.cuda.set_allocator(rmm_cupy_allocator)
adata = sc.read_h5ad("1M_brain_cells_10X.sparse.h5ad")
#adata = sc.read_h5ad( 'all_pbmcs_rna.h5ad' ) #1.9 million cells
adata.var_names_make_unique()
adata = adata[:1_000_000, :].copy()
#adata = adata[:1_700_000, :].copy()
rsc.get.anndata_to_GPU(adata)
rsc.pp.flag_gene_family(adata, gene_family_name="mt", gene_family_prefix="mt-")
rsc.pp.calculate_qc_metrics(adata, qc_vars=["mt"])

......

```

**Environment details (please complete the following information):**
 - Environment location: Bare-metal
 - Linux Distro/Architecture: Linux 3.10.0-862.el7.x86_64
 - GPU Model/Driver: [Tesla V100-SXM2-32GB and Driver Version: 515.48.07]
 - CUDA: [11.7]
 - Method of Rapids install: 
 ```
 conda create -n rapids_singlecell python=3.11.9
  conda activate rapids_singlecell
  pip install  --extra-index-url=https://pypi.nvidia.com   cudf-cu11==24.4.* dask- cudf-cu11==24.4.* cuml-cu11==24.4.*   cugraph-cu11==24.4.* cuspatial-cu11==24.4.* cuproj-cu11==24.4.*   cuxfilter-cu11==24.4.* cucim-cu11==24.4.* pylibraft-cu11==24.4.*    raft-dask-cu11==24.4.* cuvs-cu11==24.4.*
  pip install jupyterlab
```
pip list
Package                   Version
------------------------- --------------
aiohappyeyeballs          2.4.0
aiohttp                   3.10.5
aiosignal                 1.3.1
anndata                   0.10.8
anyio                     4.4.0
argon2-cffi               23.1.0
argon2-cffi-bindings      21.2.0
array_api_compat          1.8
arrow                     1.3.0
asttokens                 2.4.1
async-lru                 2.0.4
attrs                     24.2.0
babel                     2.16.0
beautifulsoup4            4.12.3
bleach                    6.1.0
bokeh                     3.4.3
cachetools                5.5.0
certifi                   2024.7.4
cffi                      1.17.0
charset-normalizer        3.3.2
click                     8.1.7
cloudpickle               3.0.0
colorcet                  3.1.0
comm                      0.2.2
contourpy                 1.2.1
cubinlinker-cu11          0.3.0.post2
cucim-cu11                24.4.0
cuda-python               11.8.3
cudf-cu11                 24.4.1
cugraph-cu11              24.4.0
cuml-cu11                 24.4.0
cuproj-cu11               24.4.0
cupy-cuda11x              13.3.0
cuspatial-cu11            24.4.0
cuvs-cu11                 24.4.0
cuxfilter-cu11            24.4.1
cycler                    0.12.1
dask                      2024.1.1
dask-cuda                 24.4.0
dask-cudf-cu11            24.4.1
dask-expr                 0.4.0
datashader                0.16.3
debugpy                   1.8.5
decorator                 5.1.1
defusedxml                0.7.1
distributed               2024.1.1
executing                 2.0.1
fastjsonschema            2.20.0
fastrlock                 0.8.2
fonttools                 4.53.1
fqdn                      1.5.1
frozenlist                1.4.1
fsspec                    2024.6.1
geopandas                 1.0.1
h11                       0.14.0
h5py                      3.11.0
holoviews                 1.19.1
httpcore                  1.0.5
httpx                     0.27.0
idna                      3.7
imageio                   2.35.1
importlib_metadata        8.4.0
ipykernel                 6.29.5
ipython                   8.26.0
isoduration               20.11.0
jedi                      0.19.1
Jinja2                    3.1.4
joblib                    1.4.2
json5                     0.9.25
jsonpointer               3.0.0
jsonschema                4.23.0
jsonschema-specifications 2023.12.1
jupyter_client            8.6.2
jupyter_core              5.7.2
jupyter-events            0.10.0
jupyter-lsp               2.2.5
jupyter_server            2.14.2
jupyter_server_proxy      4.3.0
jupyter_server_terminals  0.5.3
jupyterlab                4.2.4
jupyterlab_pygments       0.3.0
jupyterlab_server         2.27.3
kiwisolver                1.4.5
lazy_loader               0.4
legacy-api-wrap           1.4
linkify-it-py             2.0.3
llvmlite                  0.43.0
locket                    1.0.0
Markdown                  3.7
markdown-it-py            3.0.0
MarkupSafe                2.1.5
matplotlib                3.9.2
matplotlib-inline         0.1.7
mdit-py-plugins           0.4.1
mdurl                     0.1.2
mistune                   3.0.2
msgpack                   1.0.8
multidict                 6.0.5
multipledispatch          1.0.0
natsort                   8.4.0
nbclient                  0.10.0
nbconvert                 7.16.4
nbformat                  5.10.4
nest-asyncio              1.6.0
networkx                  3.3
notebook_shim             0.2.4
numba                     0.60.0
numpy                     1.26.4
nvtx                      0.2.10
overrides                 7.7.0
packaging                 24.1
pandas                    2.2.1
pandocfilters             1.5.1
panel                     1.4.5
param                     2.1.1
parso                     0.8.4
partd                     1.4.2
patsy                     0.5.6
pexpect                   4.9.0
pillow                    10.4.0
pip                       24.2
platformdirs              4.2.2
prometheus_client         0.20.0
prompt_toolkit            3.0.47
protobuf                  4.25.4
psutil                    6.0.0
ptxcompiler-cu11          0.8.1.post1
ptyprocess                0.7.0
pure_eval                 0.2.3
pyarrow                   14.0.2
pycparser                 2.22
pyct                      0.5.0
Pygments                  2.18.0
pylibcugraph-cu11         24.4.0
pylibraft-cu11            24.4.0
pynndescent               0.5.13
pynvml                    11.4.1
pyogrio                   0.9.0
pyparsing                 3.1.2
pyproj                    3.6.1
python-dateutil           2.9.0.post0
python-json-logger        2.0.7
pytz                      2024.1
pyviz_comms               3.0.3
PyYAML                    6.0.2
pyzmq                     26.2.0
raft-dask-cu11            24.4.0
rapids-dask-dependency    24.4.1
rapids_singlecell         0.10.8
referencing               0.35.1
requests                  2.32.3
rfc3339-validator         0.1.4
rfc3986-validator         0.1.1
rich                      13.7.1
rmm-cu11                  24.4.0
rpds-py                   0.20.0
scanpy                    1.10.2
scikit-image              0.22.0
scikit-learn              1.5.1
scikit-misc               0.5.1
scipy                     1.14.1
seaborn                   0.13.2
Send2Trash                1.8.3
session_info              1.0.0
setuptools                72.1.0
shapely                   2.0.6
simpervisor               1.0.0
six                       1.16.0
sniffio                   1.3.1
sortedcontainers          2.4.0
soupsieve                 2.6
stack-data                0.6.3
statsmodels               0.14.2
stdlib-list               0.10.0
tblib                     3.0.0
terminado                 0.18.1
threadpoolctl             3.5.0
tifffile                  2024.8.10
tinycss2                  1.3.0
toolz                     0.12.1
tornado                   6.4.1
tqdm                      4.66.5
traitlets                 5.14.3
treelite                  4.1.2
types-python-dateutil     2.9.0.20240821
typing_extensions         4.12.2
tzdata                    2024.1
uc-micro-py               1.0.3
ucx-py-cu11               0.37.0
umap-learn                0.5.6
uri-template              1.3.0
urllib3                   2.2.2
wcwidth                   0.2.13
webcolors                 24.8.0
webencodings              0.5.1
websocket-client          1.8.0
wheel                     0.43.0
xarray                    2024.7.0
xyzservices               2024.6.0
yarl                      1.9.4
zict                      3.0.0
zipp                      3.20.0

thank!

**Comment by Intron7** [comment]
I think there are multiple things happening. First you are running out of memory 32GB is not that much for that amount of cells. Also I wouldnt use `pool allocation` with `uvm`. Next is that you probally have more than 2**31-1 `nnz`in you sparse matrix with that amount of cells.

**Comment by lxinq2002** [comment]
Thank you for your reply.
I am not a computer engineering professional.The question I encountered while trying Rapids_Singlecell.
I will continue to test.

**Comment by adamklie** [comment]
Wanted to follow up on this. Relatively new to rapids_singlecell, but if we have a large number of cells (~1M), are we able to run this function with limited VRAM (32GB), or are we just out of luck until we get a better GPU?
