### ISSUE TITLE
Is the rapids_singlecell.tl.rank_genes_groups_logreg Supposed to Return the Pvals and Pvals-Adj?

### ISSUE THREAD

**Issue by sdettle** [scverse/rapids_singlecell#273]
According to the documentation on:
https://rapids-singlecell.readthedocs.io/en/latest/api/generated/rapids_singlecell.tl.rank_genes_groups_logreg.html
The returned structured data stored in adata.uns["rank_genes_groups"] is supposed to contain ['names'], ['scores'], ['pval'], ['p-valadj']. However, when I run this command it only returns the scores and names. When I look into the source code, I see that pval and p-valadj is never returned. There seems to be a discrepancy between the readthedocs and the source code which returns the following.

```

    adata.uns["rank_genes_groups"] = {}
    adata.uns["rank_genes_groups"]["params"] = {
        "groupby": groupby,
        "method": "logreg",
        "reference": refname,
        "use_raw": use_raw,
    }
    adata.uns["rank_genes_groups"]["scores"] = scores
    adata.uns["rank_genes_groups"]["names"] = names


```

https://github.com/scverse/rapids_singlecell/blob/main/src/rapids_singlecell/tools/_rank_gene_groups.py#L48-L220

**Comment by Intron7** [comment]
Since this is only logistic regression we don't calculate PV and adjPV. This is the same in scanpy
