### ISSUE TITLE
Add an trim parameter in bbknn function

### ISSUE THREAD

**Issue by SNOL2** [scverse/rapids_singlecell#283]
**Is your feature request related to a problem? Please describe.**
Could you add an trim option in bbknn function, which can significantly reduce the graph complexity.

**Describe the solution you'd like**
similar to scanpy.external.bbknn(trim=..., )

**Is there a CPU based implementation**
[CPU-based implementaion of bbknn trimming](https://github.com/Teichlab/bbknn/blob/95ce34b8905cbde307704a77436c354938ba0367/bbknn/matrix.py#L296)

**Comment by Intron7** [comment]
Yes I can do that. What are usual `trim` values?
