### ISSUE TITLE
[QST] Rapids_singlecell and spatialdata?

### ISSUE THREAD

**Issue by kousaa** [scverse/rapids_singlecell#284]
**What is your question?**
Hi there,

I was wondering if there a way to use rapids_singlecell with spatialdata (https://spatialdata.scverse.org/en/stable/) to run some of the existing functions faster/more efficiently when it comes to really big data. I am currently dealing with a huge Xenium dataset and I am trying to crop a whole core from a larger set of cores using the polygon_query function. My kernel keeps crushing even when I run it on a server with multiple resources. Any suggestions?

Thank you!
Anastasia

**Comment by kousaa** [comment]
Thanks so much for your quick response and that would be great!

Best,
Anastasia

**Comment by beckernick** [comment]
Hi @kousaa ! I work on RAPIDS at NVIDIA.

If you're open to it, would love to learn more about your spatial omics workflows and what the bottlenecks are. If you're interested, would love to[connect on LinkedIn](https://www.linkedin.com/in/nicholasebecker/) and chat further.

**Comment by LucaMarconato** [comment]
Hi @kousaa, as Severin mentioned, `spatialdata` doesn't support GPU-accelerated computation. Anyway in your case you may be able to address the issue by saving the `SpatialData` object to disk, and reading it again, before running `polygon_query`. Could you try please?
