### ISSUE TITLE
Support for 64-bit indptr data and multiple GPU？

### ISSUE THREAD

**Issue by YH-Zheng** [scverse/rapids_singlecell#43]
Hi, thank you for your work, which has made our single cell analysis much faster.
However, when the nnz of the matrix exceeds the maximum limit of 32 bits, the preprocessing process needs to be performed again using native scanpy, which greatly increases our time. I saw in https://github.com/NVIDIA-Genomics-Research/rapids-single-cell-examples/tree/master this work uses dask to distribute large tasks in chunks to multiple GPUs, which makes large The GPU acceleration of the amount of data can be realized, do you have any ideas in this regard? Such as support for multiple GPUs?
Thanks again for your work!

**Comment by Intron7** [comment]
Dear @YH-Zheng,

Thank you for your interest in rapids_singlecell. I want to support 64bit indptr in rsc. However there is currently a limitation with cupy when it comes to the indptr arrays. I tested a bit with using uint32 which doubles the nnzs but that's sadly to unstable. I'm already testing ways to make rapids-singlecell multi gpu enabled. Which back end I'll use is still up in the air. cunumeric is also very promising.

**Comment by YH-Zheng** [comment]
Dear @Intron7 ,

Hi Severin! Thank you for your reply, and I am looking forward to your next work. At present, I will still use the regular scanpy analysis process until I use rsc for harmony integration. 

I also noticed that the rsc of the Louvain and Leiden algorithm will generate more clusters, especially Leiden, even if the resolution is reduced, it will still generate hundreds of clusters, but it performs well in the sc (because the amount of data is too large, full iteration Time is too long, only iterate 2 times). What do you think about it?

I have not saved the Leiden result at present, the picture is the Louvain results of rsc, I think resolution=1 produces too many clusters than sc.
<img width="1100" alt="umap" src="https://github.com/scverse/rapids_singlecell/assets/48350273/01e75d1c-154e-4bb5-9063-373109676dce">

**Comment by Zethson** [comment]
See https://github.com/scverse/rapids_singlecell/issues/44 for the clustering issue

**Comment by Intron7** [comment]
So the 64 bit support in cupy might be coming. They made it a high priority https://github.com/cupy/cupy/issues/3513.

**Comment by SNOL2** [comment]
> Dear @YH-Zheng,
> 
> Thank you for your interest in rapids_singlecell. I want to support 64bit indptr in rsc. However there is currently a limitation with cupy when it comes to the indptr arrays. I tested a bit with using uint32 which doubles the nnzs but that's sadly to unstable. I'm already testing ways to make rapids-singlecell multi gpu enabled. Which back end I'll use is still up in the air. cunumeric is also very promising.

Also waiting for supporting for multiple GPUs!

**Comment by Intron7** [comment]
Multi-GPU support with dask has been released
