### ISSUE TITLE
[BUG] PCA Dense CUML23.08 CUDA12

### ISSUE THREAD

**Issue by Intron7** [scverse/rapids_singlecell#56]
Please don't use cuml-23.08 with cuda 12. 
PCA will fail for larger datasets

https://github.com/rapidsai/cuml/issues/5555

**Comment by xflicsu** [comment]
@Intron7 Hello, I also caught the error as you mentioned in the https://github.com/rapidsai/cuml/issues/5555.
So, did you fix this bug now?
And whether I need to downgrade CUDA 12 to 11.8 to work with cuml-23.08?

**Comment by xflicsu** [comment]
@Intron7 Thanks for you quick response!

**Comment by liyaodev** [comment]
@Intron7 Hi, I also encountered a similar problem, do you have a good solution now? I used `CUDA 12.1` and `rapids==24.8.0`, 3ks!

**Comment by Intron7** [comment]
I really don't have a good solution. Other than to use `CUDA-11.8`. But from what I have heard it will be fixed with `rapids-24.08`

**Comment by liyaodev** [comment]
> I really don't have a good solution. Other than to use `CUDA-11.8`. But from what I have heard it will be fixed with `rapids-24.08`

OK，thanks for you quick reply, I tried rapids==24.08a and found that the problem still exists. But the official CUDA version is 12.0 and 12.2, I use 12.1 . I will continue to try, thank you again.
