### ISSUE TITLE
[QST] What are the differences with Scanpy?

### ISSUE THREAD

**Issue by cpuritz** [scverse/rapids_singlecell#70]
In the documentation for scanpy-GPU, you state

> These functions offer accelerated near drop-in replacements for common tools porvided [sic] by scanpy.

Would you be able to elaborate on what the actual differences are? Thank you.

**Comment by Intron7** [comment]
Hey @cpuritz,
Rapids-singlecell is mainly based on CuPy and Rapids, while scanpy works with numpy, scikit-learn and numba. The switch to these packages allows for the GPU acceleration. Some rapids-singlecell functions are not feature complete (eg, normalize_total) or need slightly different implemetations (eg. regress_out or embedding_density). The goal is always to keep the results as close to scanpy as possible. For this reason most tests are 1 to 1 copys of scanpy. To see difference with scanpy you should look at the documentation and check out the [notebooks](https://github.com/scverse/rapids_singlecell/tree/main/notebooks). I always try to make it clear when there are differences in the documentation.
