### ISSUE TITLE
Implicit conversion to a NumPy array is not allowed

### ISSUE THREAD

**Issue by rjesud** [scverse/rapids_singlecell#81]
I am using version 0.9.0.

When generating the neighborhood graph, I recieve the following error:

`TypeError                                 Traceback (most recent call last)
Cell In[10], line 3
      1 rsc.pp.log1p(mergeanndata)
      2 rsc.pp.scale(mergeanndata, max_value=10)
----> 3 rsc.pp.neighbors(mergeanndata, n_neighbors=5)
      4 rsc.tl.umap(mergeanndata)

File /apps/user/gpy/envs/dev/GPUy310pascal/lib/python3.10/site-packages/rapids_singlecell/preprocessing/_neighbors.py:127, in neighbors(adata, n_neighbors, n_pcs, use_rep, random_state, metric, metric_kwds, key_added, algorithm, copy)
    122 X = _choose_representation(adata, use_rep=use_rep, n_pcs=n_pcs)
    124 nn = NearestNeighbors(
    125     n_neighbors=n_neighbors, algorithm=algorithm, metric=metric, output_type="cupy"
    126 )
--> 127 X_contiguous = np.ascontiguousarray(X, dtype=np.float32)
    128 nn.fit(X_contiguous)
    129 distances = nn.kneighbors_graph(X_contiguous, mode="distance")

File cupy/_core/core.pyx:1473, in cupy._core.core._ndarray_base.__array__()

TypeError: Implicit conversion to a NumPy array is not allowed. Please use `.get()` to construct a NumPy array explicitly.`

![image](https://github.com/scverse/rapids_singlecell/assets/46010245/2c74071e-ca88-43f1-a23a-df52e15ee31f)

Any thoughts on this error? Is this cupy related?

**Comment by Intron7** [comment]
@rjesud  No this is an oversight on my part. I had assumed that people would use PCA representation and didn't think that this could be used with a cupy array. If you transform back to cpu the bug will go away as a quick fix. I'll get to it tomorrow.

**Comment by Intron7** [comment]
Ok so 0.9.2 just got realeased this should fix the issue.

**Comment by rjesud** [comment]
Great! Thank you!
